version: "3.7"

services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - 3333:3333
    depends_on:
      - redis

    command: yarn start